options:
  service_type:
    type: string
    default: signing
    description: Which service to run - signing or admin or system-user
  keystore_secret:
    type: string
    default: abcdefg1234567890
    description: Secret code to encrypt the auth-key hash
  proxy:
    type: string
    default: ""
    description: Proxy server for accessing the Snap Store
  csrf_auth_key:
    type: string
    default: ""
    description: 32 bytes long key to protect server from cross site request forgery attacks
  channel:
    type: string
    default: stable
    description: The store channel from which the snap will be installed e.g. stable, candidate, beta, edge.
  url_host:
    type: string
    default: serial-vault:443
    description: Return URL of the service (needed for OpenID) without the protocol schema
  enable_user_auth:
    type: boolean
    default: true
    description: Enable user authentication using Ubuntu SSO
