# Identity Vault version
version: "0.3.0"
title: "Identity Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Path to the assets (${docRoot}/static)
docRoot: "."

# Backend database details
driver: "postgres"
datasource: "user={{ db.user }} host={{ db.host }} port={{ db.port }} dbname={{ db.dbname }}"

# For Database Keystore
keystore: "database"
keystoreSecret: "{{keystore_secret}}"
