# Identity Vault version
version: "0.3.0"
title: "Identity Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Path to the assets (${docRoot}/static)
docRoot: "."

# Backend database details
driver: "postgres"
datasource: "dbname={{ db.database }} host={{ db.host }} port={{ db.port }} user={{ db.user }} password={{ db.password}}"

# For Database Keystore
keystore: "database"
keystoreSecret: "{{keystore_secret}}"
