# Identity Vault version
version: "0.3.0"
title: "Identity Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Path to the assets (${docRoot}/static)
docRoot: "."

# Backend database details
driver: "postgres"
datasource: "dbname={{ db.database() }}"

# For Database Keystore
keystore: "database"
keystoreSecret: "secret code to encrypt the auth-key hash"
