# Path to the assets (${docRoot}/static)
docRoot: "."

# Service type: signing or admin
mode: {{ service_type }}

# Backend database details
driver: "postgres"
datasource: "dbname={{ db.database }} host={{ db.host }} port={{ db.port }} user={{ db.user }} password={{ db.password}}"

# For Database Keystore
keystore: "database"
keystoreSecret: "{{ keystore_secret }}"

# API keys for the signing service
apiKeys: [{{ api_keys }}]

# 32 bytes long key to protect server from cross site request forgery attacks
csrfAuthKey: "{{ csrf_auth_key }}"
